# This SPARQL replaces blank nodes
PREFIX schema: <http://schema.org/>

DELETE {
  ?blank_node ?p ?o 
}

INSERT {
  ?uuid_uri ?p ?o 
}

WHERE {
  {
    SELECT distinct ?blank_node  
    WHERE {
      ?blank_node ?any_p ?any_o . 
      FILTER (isBLANK(?blank_node))
      FILTER (?any_o IN (schema:Event, schema:Place, schema:Organization, schema:Person ))
    }
  }
  bind(UUID() as ?uuid_uri)
  ?blank_node ?p ?o 
}