name: Fetch ADC-659 Entities
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 1 6,12 *
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Action setup
      uses: culturecreates/artsdata-pipeline-action@v3
      with:
        mode: fetch-push
        artifact: adc659-ca
        publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
        downloadFile: output/adc659-entities.jsonld
        page-url: https://www.adc659.ca/members/?page_dbbb0=
        entity-identifier: div.um-member-cover-e a
        is-paginated: "true"
        fetch-urls-headlessly: "true"
        token: "${{ secrets.GITHUB_TOKEN }}"
        html-extract-config: |
          {
            "entity_type": "http://schema.org/Person",
            "extract": {
              "http://schema.org/email": {
                "xpath": "normalize-space(//div[contains(@id,\"user_email-113\")])",
                "array": "true"
              },
              "http://schema.org/name": {
                "xpath": "normalize-space(//div[@class=\"um-name\"])",
                "array": "true"
              },
              "http://schema.org/telephone": {
                "xpath": "normalize-space(//div[contains(@id,\"phone_number-113\")])",
                "array": "true"
              },
              "http://schema.org/url": {
                "xpath": "normalize-space(//div[contains(@id,\"user_url-113\")])",
                "array": "true"
              },
              "http://schema.org/addressRegion": {
                "xpath": "normalize-space(//div[contains(@id,\"residence_Region-113\")])",
                "array": "true"
              },
              "http://www.wikidata.org/prop/direct/P2013": {
                "xpath": "//div[contains(@id,\"facebook-113\")]/a/@href",
                "array": "true",
                "uri": "true"
              },
              "http://www.wikidata.org/prop/direct/P2003": {
                "xpath": "//div[contains(@id,\"instagram-113\")]/a/@href",
                "array": "true",
                "uri": "true"
              },
              "http://www.adc659.ca/vocabulary#memberType": {
                "xpath": "normalize-space(//div[contains(@id,\"role_select-113\")])",
                "array": "true"
              },
              "http://www.adc659.ca/vocabulary#designDiscipline": {
                "xpath": "normalize-space(//div[contains(@id,\"design_discipline-113\")])",
                "array": "true"
              },
              "http://www.adc659.ca/vocabulary#pronounPreference": {
                "xpath": "normalize-space(//div[contains(@id,\"pronoun_preference-113\")])",
                "array": "true"
              },
              "http://www.adc659.ca/vocabulary#availableForWork": {
                "xpath": "normalize-space(//div[contains(@id,\"available_for_work-113\")])",
                "array": "true"
              },
              "http://www.adc659.ca/vocabulary#availableForAssistantassociate": {
                "xpath": "normalize-space(//div[contains(@id,\"available_for_assistantassociate-113\")])",
                "array": "true"
              },
              "http://schema.org/hasOccupation": {
                "xpath": "normalize-space(//div[contains(@id,'design_discipline-113')])",
                "array": "true",
                "transform": {
                  "function": "split",
                  "args": [","]
                }
              },
              "http://schema.org/knowsLanguage": {
                "xpath": "normalize-space(//div[contains(@id,\"languages-113\")])",
                "array": "true",
                "transform": {
                  "function": "split",
                  "args": [","]
                }
              }
            }
          }
