name: Fetch Agoradanse Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2.0.2
        with:
          mode: "fetch-push"
          artifact: "agoradanse-com"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "agoradanse-events.jsonld"
          page-url: "https://agoradanse.com/evenement/"
          entity-identifier: "div.x-container.max a"
          token: "${{ secrets.GITHUB_TOKEN }}"