name: Fetch Capitol Theatre Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
      
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://capitoltheatre.ca/events/list/?tribe_paged="
        entity_identifier: "h3.tribe-events-list-event-title a"
        file_name: "capitoltheatre-events.jsonld"
        is_paginated: "true"
        headless: "false"
      
  artsdata-push:
    runs-on: ubuntu-latest
    needs: call-workflow-to-fetch-data
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v1.1.0
        with:
          artifact: capitoltheatre-ca
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: https://raw.githubusercontent.com/culturecreates/artsdata-orion/${{ needs.call-workflow-to-fetch-data.outputs.commit-hash }}/output/capitoltheatre-events.jsonld
