name: Fetch Capitolnb Events

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 12 * * 3' #runs every week on wednesday at noon UTC (around 7 AM EDT)

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2
        with:
          mode: "fetch-push"
          artifact: "capitol-nb-ca"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "capitolnb-events.jsonld"
          page-url: "https://capitol.nb.ca/en/tickets-events?start="
          entity-identifier: "div.fc-item-block-standard-wrapper.odd a, div.fc-item-block-standard-wrapper.even a"
          is-paginated: "0"
          headless: "true"
          offset: "12"
          token: "${{ secrets.GITHUB_TOKEN }}"
