name: Fetch capitol-nb-ca Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 3' #runs every week on wednesday at noon UTC (around 7 AM EDT)

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "capitol-nb-ca"
          publisher: "https://github.com/fjjulien#this"
          downloadFile: "output/capitolnb-events.jsonld"
          page-url: "https://capitol.nb.ca/en/tickets-events?start=,https://capitol.nb.ca/fr/spectacles-et-billets?start="
          entity-identifier: "div.fc-item-block-standard-wrapper.odd a, div.fc-item-block-standard-wrapper.even a"
          is-paginated: "0"
          offset: "12"
          token: "${{ secrets.GITHUB_TOKEN }}"
