name: Fetch Capitolnb Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1'  # Runs every Monday at 10 AM EST

jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.get_commit_hash.outputs.commit-hash }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Main Script
      run: |
          bundle exec ruby src/main.rb \
          https://capitol.nb.ca/en/tickets-events \
          "div.fc-item-block-standard-wrapper.odd a, div.fc-item-block-standard-wrapper.even a" \
          output/capitolnb-events.jsonld \
          false \
          true

    - name: Replace location
      run: |
        FILE="output/capitolnb-events.jsonld"
        sed -i 's/"@value": "Capitol Theatre"/"@id": "http:\/\/kg.artsdata.ca\/resource\/K11-116"/g' "$FILE"
        sed -i 's/"@value": "Empress Theatre"/"@id": "http:\/\/kg.artsdata.ca\/resource\/K11-116"/g' "$FILE"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add output/capitolnb-events.jsonld
        git commit -m "Add data generated by the script"
        git push

    - name: Get commit hash
      id: get_commit_hash
      run: |
        commit_hash=$(git rev-parse HEAD)
        echo "commit-hash=$commit_hash" >> $GITHUB_OUTPUT
      
      

  artsdata-push:
    runs-on: ubuntu-latest
    needs: fetch-and-commit-data
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v1.1.0
        with:
          artifact: capitol-nb-ca
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: https://raw.githubusercontent.com/culturecreates/artsdata-orion/${{ needs.fetch-and-commit-data.outputs.commit-hash }}/output/capitolnb-events.jsonld

