name: Fetch Capitol Theatre Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
      
jobs:
  call-workflow-to-fetch-and-push-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://capitoltheatre.ca/events/list/?tribe_paged="
        entity_identifier: "h3.tribe-events-list-event-title a"
        file_name: "capitoltheatre-events.jsonld"
        is_paginated: "true"
        headless: "false"
        artifact: "capitoltheatre-ca"
    secrets:
        PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}