name: casadelpopolo-com

on:
  workflow_dispatch:

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "casadelpopolo-com"
          publisher: "https://github.com/saumier#this"
          page-url: "https://casadelpopolo.com"
          headless: true
          report-callback-url: https://webhook.site/2716ad6e-e9c6-41cf-8ecc-d1c633803d1c
          token: "${{ secrets.GITHUB_TOKEN }}"
