name: Fetch Co-Motion Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 3'

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "co-motion-ca"
          publisher: "https://github.com/fjjulien#this"
          page-url: "https://co-motion.ca/spectacles/?page="
          entity-identifier: "a[href^='/spectacles']:not([href^='/spectacles/?'])"
          is-paginated: "true"
          headless: "true"
          token: "${{ secrets.GITHUB_TOKEN }}"
