name: Fetch Culture Gaspésie Events

on:
  workflow_dispatch:
  schedule:
  - cron: '30 6 * * 2'
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2
        with:
          mode: "fetch-push"
          artifact: "culturegaspesie-org"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "culturegaspesie-events.jsonld"
          page-url: "https://culturegaspesie.org/event-sitemap.xml"
          entity-identifier: "loc"
          token: "${{ secrets.GITHUB_TOKEN }}"
