name: Reusable workflow to push into artsdata

on:
  workflow_call:
    inputs:
      page_url:
        required: true
        type: string
      entity_identifier:
        required: true
        type: string
      file_name:
        required: true
        type: string
      is_paginated:
        required: true
        type: string
      base_url:
        required: false
        type: string
      artifact_name:
        required: true
        type: string
    secrets:
      publisher_uri:
        required: true


jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Main Script
      run: |
        bundle exec ruby src/main.rb \
        ${{ inputs.page_url }} \
        ${{ inputs.entity_identifier }} \
        output/${{ inputs.file_name }} \
        ${{ inputs.is_paginated}} \
        ${{ inputs.base_url}} 
    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add "output/${{ inputs.file_name }}"
        git commit -m "Add data generated by the script"
        git push

    - name: Set current date as output
      id: version  
      run: echo "dumpdate=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Set download URL
      id: output_file
      run: echo "download_url=https://raw.githubusercontent.com/culturecreates/artsdata-orion/main/output/${{ inputs.file_name }}" >> $GITHUB_OUTPUT
    - name: Push to artsdata
      run: |
        curl \
        -H 'Content-Type: application/json' \
        -X POST http://api.artsdata.ca/databus/  \
        --data '{ "artifact": "${{ inputs.artifact_name }}",
                "comment": "Entities from ${{ inputs.page_url }}",
                "publisher": "${{ secrets.publisher_uri }}",
                "group": "${{ github.event.repository.name }}",
                "version": "${{ steps.version.outputs.dumpdate }}",
                "downloadUrl": "${{ steps.output_file.outputs.download_url }}",
                "downloadFile": "${{ github.event.inputs.file_name }}",
                "reportCallbackUrl": "https://huginn-staging.herokuapp.com/users/1/web_requests/273/databus"
                }'
        
    
