name: Reusable workflow to fetch JSON-LD data.

on:
  workflow_call:
    inputs:
      page_url:
        required: true
        type: string
      entity_identifier:
        required: true
        type: string
      file_name:
        required: true
        type: string
      is_paginated:
        required: true
        type: string
      headless:
        required: true
        type: string
      artifact:
        required: true
        type: string
    secrets:
      PUBLISHER_URI_GREGORY:
        required: true

jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/fetch-data.yml
    with:
        page_url: ${{inputs.page_url}}
        entity_identifier: ${{inputs.entity_identifier}}
        file_name: ${{inputs.file_name}}
        is_paginated: ${{inputs.is_paginated}}
        headless: ${{inputs.headless}}    

  artsdata-push:
    runs-on: ubuntu-latest
    needs: call-workflow-to-fetch-data
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v1.1.0
        with:
          artifact: ${{ inputs.artifact }}
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: https://raw.githubusercontent.com/culturecreates/artsdata-orion/${{ needs.call-workflow-to-fetch-data.outputs.commit-hash }}/output/${{ inputs.file_name }}
    
