name: Fetch grandsballets-com Events

on:
  workflow_dispatch:
 
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "grandsballets-com"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "output/grandsballets-com.jsonld"
          page-url: "https://grandsballets.com/"
          token: "${{ secrets.GITHUB_TOKEN }}"
