name: Fetch Imperial-Theatre Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'
      
jobs:
  call-workflow-to-fetch-and-push-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://imperialtheatre.ca/events/?_paged="
        entity_identifier: "div.fl-post-image a"
        file_name: "imperialtheatre-events.jsonld"
        is_paginated: "true"
        headless: "false"
        artifact: "imperialtheatre-ca"
    secrets:
        PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}