name: Fetch Imperial-Theatre Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "imperialtheatre-ca"
          publisher: "https://github.com/fjjulien#this"
          downloadFile: "output/imperialtheatre-events.jsonld"
          page-url: "https://imperialtheatre.ca/events/?_paged="
          entity-identifier: "div.fl-post-image a"
          is-paginated: "true"
          token: "${{ secrets.GITHUB_TOKEN }}"
