name: japanesecanadianartists-com

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 4 * *'
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v4
        with:
          mode: "fetch-push"
          artifact: "japanesecanadianartists-com"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "output/japanesecanadianartists-com-events.jsonld"
          page-url: "https://japanesecanadianartists.com/artist/"
          entity-identifier: "h1.entry-title a"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
