name: Fetch Kingston-Grand Events

on:
    workflow_dispatch:
    schedule:
      - cron: '0 14 * * 1'    
jobs:
  call-workflow-to-fetch-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://www.kingstongrand.ca/events"
        entity_identifier: "div.image a"
        file_name: "kingston-grand-events.jsonld"
        is_paginated: "false"
        headless: "false"

  artsdata-push:
    runs-on: ubuntu-latest
    needs: call-workflow-to-fetch-data
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v1.1.0
        with:
          artifact: kingstongrand-ca
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: https://raw.githubusercontent.com/culturecreates/artsdata-orion/${{ needs.call-workflow-to-fetch-data.outputs.commit-hash }}/output/kingston-grand-events.jsonld

