name: Fetch Kingston-Grand Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1'    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2.0.0
        with:
          mode: "fetch-push"
          artifact: "kingstongrand-ca"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "kingston-grand-events.jsonld"
          page-url: "https://www.kingstongrand.ca/events"
          entity-identifier: "div.image a"
          token: "${{ secrets.GITHUB_TOKEN }}"