name: Fetch Kingston-Grand Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1'    
jobs:
  call-workflow-to-fetch-and-push-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://www.kingstongrand.ca/events"
        entity_identifier: "div.image a"
        file_name: "kingston-grand-events.jsonld"
        is_paginated: "false"
        headless: "false"
        artifact: "kingstongrand-ca"
    secrets:
        PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
