name: Fetch larotonde-qc-ca

on:
  workflow_dispatch:
  
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "larotonde-qc-ca"
          publisher: "https://github.com/fjjulien#this"
          page-url: "https://www.larotonde.qc.ca/sitemap.xml"
          entity-identifier: "a[href*='/programmation/']"
          fetch-urls-headlessly: true
          token: "${{ secrets.GITHUB_TOKEN }}"
