name: Reusable workflow to push into artsdata

on:
  workflow_dispatch:
    inputs:
      page_url:
        description: 'Page URL to loop pages'
        required: true
      entity_identifier:
        description: 'Entity html tag'
        required: true
      file_name:
        description: 'File Name'
        required: true
      is_paginated: 
        description: 'Set as true if the pages are paginated'
        required: true
      base_url:
        description: 'Base URL (base_url is optional in case of relative hrefs)'
        required: false
      artifact_name:
        description: 'Artifact name to push into artsdata'
        required: true

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Main Script
      run: |
        bundle exec ruby src/main.rb \
        ${{ github.event.inputs.page_url }} \
        ${{ github.event.inputs.entity_identifier }} \
        output/${{ github.event.inputs.file_name }} \
        ${{ github.event.inputs.is_paginated}} \
        ${{ github.event.inputs.base_url}} 
    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add "output/${{ github.event.inputs.file_name }}"
        git commit -m "Add data generated by the script"
        git push

    - name: Set current date as output
      id: version  
      run: echo "dumpdate=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Set download URL
      id: output_file
      run: echo "download_url=https://raw.githubusercontent.com/culturecreates/artsdata-orion/main/output/${{ github.event.inputs.file_name }}" >> $GITHUB_OUTPUT
    - name: Push to artsdata
      run: |
        curl \
        -H 'Content-Type: application/json' \
        -X POST http://api.artsdata.ca/databus/  \
        --data '{ "artifact": "${{ inputs.artifact_name }}",
                "comment": "Entities from ${{ inputs.page_url }}",
                "publisher": "${{ secrets.PUBLISHER_URI_GREGORY }}",
                "group": "${{ github.event.repository.name }}",
                "version": "${{ steps.version.outputs.dumpdate }}",
                "downloadUrl": "${{ steps.output_file.outputs.download_url }}",
                "downloadFile": "${{ github.event.inputs.file_name }}",
                "reportCallbackUrl": "https://huginn-staging.herokuapp.com/users/1/web_requests/273/databus"
                }'
        
    
