name: Fetch OSAC Events

on:
  workflow_dispatch:
      
jobs:
  call-workflow-to-fetch-and-push-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://www.osac.ca/performing-arts/performances?run=patours"
        entity_identifier: "td a"
        file_name: "osac-events.jsonld"
        is_paginated: "false"
        headless: "false"  
        artifact: "osac-ca"
    secrets:
        PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}