name: Fetch OSAC Events

on:
  workflow_dispatch:
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2.0.3
        with:
          mode: "fetch-push"
          artifact: "osac-ca"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "osac-events.jsonld"
          page-url: "https://www.osac.ca/performing-arts/performances?run=patours"
          entity-identifier: "td a"
          token: "${{ secrets.GITHUB_TOKEN }}"