name: Fetch RCAAQ Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'
      
jobs:
  call-workflow-to-fetch-and-push-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://reseauartactuel.org/liste_evenements/page/"
        entity_identifier: "h3.tribe-events-list-event-title a"
        file_name: "rcaaq-events.jsonld"
        is_paginated: "true"
        headless: "false"  
        artifact: "reseauartactuel-org"
    secrets:
        PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}