name: Fetch RCAAQ Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2.0.0
        with:
          mode: "fetch-push"
          artifact: "reseauartactuel-org"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "rcaaq-events.jsonld"
          page-url: "https://reseauartactuel.org/liste_evenements/page/"
          entity-identifier: "h3.tribe-events-list-event-title a"
          is-paginated: "true"
          token: "${{ secrets.GITHUB_TOKEN }}"