name: Fetch spectart.com Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 3'
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2.0.0
        with:
          mode: "fetch-push"
          artifact: "spectart-com-events"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "spectart-com-events.jsonld"
          page-url: "https://spectart.com/programmation/"
          entity-identifier: "a.thumbnail"
          token: "${{ secrets.GITHUB_TOKEN }}"
