name: Fetch spectart.com Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 3'
jobs:
  call-workflow-to-fetch-and-push-data:
    uses: ./.github/workflows/fetch-and-push-to-artsdata.yml
    with:
        page_url: "https://spectart.com/programmation/"
        entity_identifier: "a.thumbnail"
        file_name: "spectart-com-events.jsonld"
        is_paginated: "false"
        headless: "false"    
        artifact: "spectart-com-events"
    secrets:
        PUBLISHER_URI_GREGORY: ${{ secrets.PUBLISHER_URI_GREGORY }}
