name: Fetch theplayhouse-ca Events

on:
  workflow_dispatch:
  schedule:
  - cron: '30 5 * * 2'
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "theplayhouse-ca"
          publisher: "https://github.com/fjjulien#this"
          page-url: "https://theplayhouse.ca/en/sitemap.xml,https://theplayhouse.ca/fr/sitemap.xml"
          entity-identifier: "loc"
          token: "${{ secrets.GITHUB_TOKEN }}"
