name: Fetch Ticketpro Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 3'
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v2.0.3
        with:
          mode: "fetch-push"
          artifact: "ticketpro-events"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "ticketpro-events.jsonld"
          page-url: "https://ww1.ticketpro.ca/?languageid=-1"
          entity-identifier: "div.item.itemblockTextAnime a"
          token: "${{ secrets.GITHUB_TOKEN }}"